#!/bin/bash
function do_test() {
  FILE=$1
  LOG="$FILE.log"

  ./"$FILE" > ./"$LOG" 2>&1 | true
  #./llvmir DyCheck "$FILE" > "$LLCMIR"  # Silence the segfault
  #./tests/dynamicCheck/LLVMIR DyCheck "$FILE" > "$LLCMIR" 2>&1 | true

}

for i in tests/dynamicCheck/*.ll; do do_test "$i"; done