#!/bin/bash

set -e  # Terminate on errors

LLVMIR=./llvmir
LLVMAS=llvm-as-10
CLANG=clang-10

function fail() {
  echo "ERROR: $BASENAME ($CFGNAME): $1"
  echo "Logfile: $LOGFILE"
  exit 1
}

# prepare <qfile>, expects $FLAGS, $CFGNAME to be set
function prepare() {
  QFILE="$1"

  BASENAME="${QFILE%.q}"
  STEM=${BASENAME##*/}
  DIRNAME="${BASENAME%/*}"

  OUTDIR=$DIRNAME/out
  OUTBASE=$OUTDIR/$STEM.$CFGNAME
  mkdir -p "$OUTDIR"

  echo -n "Testing $BASENAME ($CFGNAME), flags $FLAGS: "

  # Input files
  # QFILE
  CFILE="$BASENAME.c"

  # Output files
  LLFILE="$OUTBASE.ll"
  OUTFILE="$OUTBASE.out"
  LOGFILE="$OUTBASE.log"

  rm -rf $LLFILE $OUTFILE $LOGFILE
}

function compile() {
  $LLVMIR $FLAGS $QFILE > $LLFILE 2>$LOGFILE || fail "Compilation error"

  $LLVMAS -disable-output $LLFILE 1>$LOGFILE 2>&1 || fail "Invalid llvm text generated by compiler"
  $CLANG -O2 -Wall -Wextra --rtlib=compiler-rt -g -o "$OUTFILE" "$CFILE" "$LLFILE" 1>$LOGFILE 2>&1 || fail "Clang compilation error"
}

function run_test() {
  ./"$OUTFILE" > "$LOGFILE" 2>&1 || fail "Running test failed"
}

function check_success(){
  REGEXP="Success!"

  grep -q "$REGEXP" "$LOGFILE" || fail "No '$REGEXP', did not pass the test"
  echo "Success!"
}

function do_test() {
  prepare $1
  compile
  run_test
  check_success
}

function do_tests() {
  FLAGS=$1
  CFGNAME=$2

  for i in tests/validTest/*.q; do
    do_test $i
  done

}

do_tests DyCheck dy
do_tests notDyCheck ndy

